--SELECT its.* FROM dbamv.IT_SAME its WHERE its.CD_ATENDIMENTO = '5018720';
--SELECT itsp.* FROM dbamv.IT_SAME_PROTOCOLOS itsp WHERE itsp.CD_ATENDIMENTO = '5018720' ORDER BY itsp.CD_PROTOCOLO DESC;
--SELECT * FROM dbamv.PROTOCOLOS WHERE CD_PROTOCOLO IN (155005,155005,154285,154262);

SELECT 
tot.CD_ATENDIMENTO, 
tot.CD_PROTOCOLO,
tot.CD_PORTADOR,
tot.DS_PORTADOR,
tot.HR_ENTRADA,
tot.CD_PORTADOR_DESTINO,
tot.DS_PORTADOR_DESTINO,
tot.HR_ENTRADA,
((tot.HR_SAIDA - tot.HR_ENTRADA)*24*60) AS DIF_MIN,
dbamv.FNC_MINUTOS_DIAS_HORAS_MIN(((tot.HR_SAIDA - tot.HR_ENTRADA)*24*60)) AS DIF_MIN_DESC
FROM(SELECT res.*,
      (SELECT prot.HR_SAIDA FROM dbamv.PROTOCOLOS prot WHERE prot.CD_PROTOCOLO = res.CD_PROTOCOLO_ANTERIOR) AS HR_ENTRADA,
      p.DS_PORTADOR, pdest.DS_PORTADOR AS DS_PORTADOR_DESTINO
      FROM (SELECT itsp.CD_ATENDIMENTO, itsp.CD_PROTOCOLO, 
            pr.CD_PORTADOR, pr.CD_PORTADOR_DESTINO, pr.HR_SAIDA,
            (SELECT MAX(CD_PROTOCOLO) 
             FROM dbamv.IT_SAME_PROTOCOLOS aux
             WHERE aux.CD_ATENDIMENTO = itsp.CD_ATENDIMENTO
             AND aux.CD_PROTOCOLO < pr.CD_PROTOCOLO) AS CD_PROTOCOLO_ANTERIOR
            --itsp.*, pr.*
            FROM dbamv.IT_SAME_PROTOCOLOS itsp 
            INNER JOIN (SELECT CD_PROTOCOLO, CD_PORTADOR, CD_PORTADOR_DESTINO, HR_SAIDA 
                        FROM dbamv.PROTOCOLOS 
                        WHERE HR_SAIDA >= SYSDATE - 60) pr
              ON pr.CD_PROTOCOLO = itsp.CD_PROTOCOLO
            --WHERE itsp.CD_ATENDIMENTO = '5018720' 
      ) res
LEFT JOIN (SELECT * FROM dbamv.PORTADORES) p
  ON p.CD_PORTADOR = res.CD_PORTADOR
LEFT JOIN (SELECT * FROM dbamv.PORTADORES) pdest
  ON pdest.CD_PORTADOR = res.CD_PORTADOR_DESTINO
WHERE res.CD_PROTOCOLO_ANTERIOR IS NOT NULL) tot
WHERE EXTRACT(DAY FROM tot.HR_ENTRADA) = 12
AND EXTRACT(MONTH FROM tot.HR_ENTRADA) = 05
AND EXTRACT(YEAR FROM tot.HR_ENTRADA) = 2023
